#!/usr/bin/env python3
"""Turn .ar84 packages into calculator modules, so `pacman -Sy` / `pacman -S` can use them.

  python3 tools/ar84pack.py --repo mine repos/mine            every *.ar84 in the folder
  python3 tools/ar84pack.py --repo mine a.ar84 b.ar84 --out out
  python3 tools/ar84pack.py --repo mine repos/mine --send     also upload (uses evo_usb)

For each package: K<6 hex><n>.py  (part n of the package text, as a LINES tuple),
for the repository: QR<NAME>.py   (ROWS: name, version, module id, parts, depends, description),
and R84REG.py                     (REPOS: every repository the calculator should read).
Module names are limited to 8 capital letters/digits by the calculator, hence the hashed ids.
The registry lists --also repositories plus, with --send, every QR* program found on the
calculator (list_files), so uploading one repository never forgets the others. The whole
repository is rebuilt from its folder each time (the old index cannot be read back), and
modules of packages you removed from a folder stay on the calculator until you delete them.
Packages are checked with the same parser pacman uses before anything is written.
"""
import hashlib
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
from A84PM import PkgError, ok_name, ok_ver
from A84PS import scan

PART_CHARS = 5000          # source size of one part module (compile memory ~4x on the calculator)
MAX_PARTS = 9


class Text:
    """Just enough of a VFS for A84PM.scan: lines of one package."""

    def __init__(self, text):
        self.text = text

    def lines(self, path):
        t = self.text
        if t.endswith("\n"):
            t = t[:-1]
        return iter(t.split("\n"))


def check_repo_name(r):
    if not re.fullmatch(r"[a-z0-9]{1,6}", r):
        raise SystemExit("repository names are 1-6 lowercase letters/digits: " + r)


def package_parts(lines, part_chars):
    parts = [[]]
    size = 0
    for line in lines:
        cost = len(repr(line)) + 6
        if size + cost > part_chars and parts[-1]:
            parts.append([])
            size = 0
        parts[-1].append(line)
        size += cost
    return parts


def part_source(name, version, n, lines):
    out = "# Arch84 package %s %s, part %d (generated by ar84pack)\nLINES = (\n" % (name, version, n)
    for line in lines:
        out += "    " + repr(line) + ",\n"
    return out + ")\n"


def build_repo(repo, files, outdir, part_chars=PART_CHARS):
    """-> {filename: source} for the repository (packages + index)."""
    check_repo_name(repo)
    out = {}
    rows = []
    used = {}
    for path in files:
        with open(path, encoding="utf-8") as f:
            text = f.read()
        try:
            meta = scan(Text(text), path)
        except PkgError as e:
            raise SystemExit("%s: %s" % (path, e))
        name, ver = meta["name"], meta["version"]
        if (name, ver) in used.values():
            raise SystemExit("duplicate package %s %s" % (name, ver))
        mid = "K" + hashlib.sha1((repo + ":" + name + "-" + ver).encode()).hexdigest()[:6].upper()
        if mid in used:
            raise SystemExit("module id clash between %s and %s: rename one version" % (used[mid], (name, ver)))
        used[mid] = (name, ver)
        lines = text.rstrip("\n").split("\n")
        parts = package_parts(lines, part_chars)
        if len(parts) > MAX_PARTS:
            raise SystemExit("%s is too big (%d parts, limit %d)" % (path, len(parts), MAX_PARTS))
        for i, p in enumerate(parts):
            out[mid + str(i) + ".py"] = part_source(name, ver, i, p)
        rows.append((name, ver, mid, len(parts), " ".join(meta["depends"]), meta["desc"]))
    rows.sort()
    idx = "# Arch84 repository %s (generated by ar84pack)\nROWS = (\n" % repo
    for r in rows:
        idx += "    " + repr(r) + ",\n"
    out["QR" + repo.upper() + ".py"] = idx + ")\n"
    return out


def registry_source(repos):
    repos = sorted(set(repos))
    return "# Arch84 repository list (generated by ar84pack)\nREPOS = (" + "".join(repr(r) + ", " for r in repos) + ")\n"


def device_repos(names):
    return [n[2:].lower() for n in names if re.fullmatch(r"QR[A-Z0-9]{1,6}", n)]


def main(argv):
    repo = None
    out = "ar84out"
    also = []
    send = False
    src = []
    i = 0
    while i < len(argv):
        a = argv[i]
        if a == "--repo":
            repo = argv[i + 1]
            i += 2
        elif a == "--out":
            out = argv[i + 1]
            i += 2
        elif a == "--also":
            also += argv[i + 1].split(",")
            i += 2
        elif a == "--send":
            send = True
            i += 1
        else:
            src.append(a)
            i += 1
    if repo is None or not src:
        raise SystemExit(__doc__)
    files = []
    for s in src:
        if os.path.isdir(s):
            files += sorted(os.path.join(s, f) for f in os.listdir(s) if f.endswith(".ar84"))
        else:
            files.append(s)
    if not files:
        raise SystemExit("no .ar84 files given")
    mods = build_repo(repo, files, out)
    repos = [repo] + also
    e = None
    if send:
        import evo_usb as e
        repos += device_repos([f["name"] for f in e.list_files()])
    mods["R84REG.py"] = registry_source(repos)
    os.makedirs(out, exist_ok=True)
    for fn, text in mods.items():
        with open(os.path.join(out, fn), "w", encoding="utf-8") as f:
            f.write(text)
        if e is not None:
            n = fn[:-3]
            if not e.is_valid_evo_python_name(n):
                raise SystemExit("invalid calculator program name: " + n)
    print("wrote %d modules to %s (repositories: %s)" % (len(mods), out, " ".join(sorted(set(repos)))))
    if send:
        for fn in mods:
            e.send_file(os.path.join(out, fn), fn[:-3])
            print("sent " + fn[:-3])


if __name__ == "__main__":
    main(sys.argv[1:])
