#!/usr/bin/env python3
"""Generate A84T1..A84T4 (the selftest cases, one quarter per module) from A84TD + A84TY.

The calculator cannot keep all 182 cases in RAM next to the lazy command
modules, so `selftest` loads one quarter at a time. A84TD / A84TY stay the
hand-edited sources; run this after changing them (a test checks they agree).
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
PARTS = 4
NCHECKS = 10        # A84TX.CHECKS run first, as items 1..10


def generate():
    import A84TD
    import A84TY
    cases = A84TD.CASES + A84TY.CASES2
    total = NCHECKS + len(cases)
    out = {}
    for p in range(1, PARTS + 1):
        rows = []
        first = None
        for i, c in enumerate(cases):
            n = NCHECKS + i + 1
            if (n - 1) * PARTS // total == p - 1:
                if first is None:
                    first = n
                rows.append(c)
        text = ("# A84T%d: selftest cases, part %d of %d (generated by tools/gen_selftest.py from\n"
                "# A84TD + A84TY: edit those, not this). Arch84 module, loaded by selftest.\n"
                "START = %d\nCASES = [\n" % (p, p, PARTS, first or total + 1))
        for c in rows:
            text += "    %r,\n" % (c,)
        text += "]\n"
        out["A84T%d.py" % p] = text
    return out


if __name__ == "__main__":
    for name, text in generate().items():
        with open(os.path.join(ROOT, name), "w") as f:
            f.write(text)
        print(name, len(text))
